name: Run Automation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Set environment variables for CI
      - name: Set environment variables
        run: |
          echo "executionType=CI" >> $GITHUB_ENV
          echo "browserType=Chrome" >> $GITHUB_ENV

      # 4️⃣ Create required output directories
      - name: Create output directories
        run: |
          mkdir -p test-outputs/allure-results
          mkdir -p test-outputs/Screenshots
          mkdir -p test-outputs/Logs

      # 5️⃣ Install Chrome + ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          chromedriver-version: latest

      # 6️⃣ Install Firefox + GeckoDriver (optional)
      - name: Install Firefox
        run: sudo apt-get install -y firefox

      - name: Install GeckoDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      # 7️⃣ Run tests
      - name: Run tests with Maven
        run: mvn clean test

      # 8️⃣ Install Allure
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # 9️⃣ Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:report

      # 🔟 Upload Allure Report Artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./test-outputs/allure-report
